name: Java CI/CD

on:
  push:
    branches:
      - main

env:
  APP_NAME: hotel-lucena
  JAVA_VERSION: 11
  TOMCAT_VERSION: 9.0.46
  GCP_PROJECT: hotel-lucena
  GCP_REGION: southamerica-east1
  GCP_CLUSTER: hotel-lucena-cluster
  GCP_ZONE: southamerica-east1
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn clean package
      
    - name: Run JUnit tests
      run: mvn test
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
          service_account_key: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT }}
          
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.GCP_CLUSTER }} --region=${{ env.GCP_REGION }}
        kubectl config current-context
        
    - name: Deploy to GKE
      run: |
        export IMAGE=gcr.io/${{ env.GCP_PROJECT }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker build $IMAGE -f ./ .
        docker tag $IMAGE $IMAGE-dev
        docker push $IMAGE
        kubectl apply -f k8s/
        
    - name: Verify deployment
      run: |
        curl http://$(kubectl get service myapp-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
